package chapter16;

public class ExceptionMain_02 {
	public static void main(String[] args) {
		int var = 50;
		int data = 0;
		
		try {
			System.out.println(var/data);
		}catch (NumberFormatException | ArithmeticException nae) {
			// TODO: handle exception
		}catch (Exception e) {
			// TODO: handle exception
			System.out.println("예외처리 ");
			System.out.println(e.getMessage());
		}//trycatch
		System.out.println("program end");
	}//main
}
